# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pangolin}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Theo Hultberg"]
  s.date = %q{2009-12-07}
  s.description = %q{Ant is a nice tool for writing Java build scripts, but Rake is nicer. The only thing missing from Rake is a way to run javac and jar, and although it's easy to run these as shell scripts you have to wait for the JVM to start. In combination with JRuby this gem lets you run javac and jar in your Rake scripts without exec'ing.}
  s.email = %q{theo@iconara.net}
  s.extensions = ["Rakefile"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/compile/Rakefile",
     "examples/compile/src/com/example/HelloWorld.java",
     "examples/errors/Rakefile",
     "examples/errors/src/com/example/HelloWorld.java",
     "examples/package/Rakefile",
     "examples/package/src/com/example/HelloWorld.java",
     "examples/test/Rakefile",
     "examples/test/src/com/example/HelloWorld.java",
     "examples/test/test/com/example/TestHelloWorld.java",
     "lib/pangolin.rb",
     "lib/pangolin/common/jar_common.rb",
     "lib/pangolin/common/javac_common.rb",
     "lib/pangolin/common/junit_common.rb",
     "lib/pangolin/exec/jar.rb",
     "lib/pangolin/exec/javac.rb",
     "lib/pangolin/exec/junit.rb",
     "lib/pangolin/java/jar.rb",
     "lib/pangolin/java/javac.rb",
     "lib/pangolin/java/junit.rb",
     "lib/pangolin/output/formatting.rb",
     "pangolin.gemspec",
     "spec/integration/data/classes/com/example/HelloWorld.class",
     "spec/integration/data/sources/com/example/Error.java",
     "spec/integration/data/sources/com/example/HelloWorld.java",
     "spec/integration/data/tests/com/example/HelloWorld.class",
     "spec/integration/data/tests/com/example/TestHelloWorld.class",
     "spec/integration/jar_intg_spec.rb",
     "spec/integration/javac_intg_spec.rb",
     "spec/integration/junit_intg_spec.rb",
     "spec/jar_cmd_spec.rb",
     "spec/jar_spec.rb",
     "spec/javac_cmd_spec.rb",
     "spec/javac_spec.rb",
     "spec/junit_cmd_spec.rb",
     "spec/junit_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/gem.rake",
     "tasks/rdoc.rake",
     "tasks/spec.rake"
  ]
  s.homepage = %q{http://github.com/iconara/pangolin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby wrappers for javac and jar that don't just exec}
  s.test_files = [
    "spec/integration/jar_intg_spec.rb",
     "spec/integration/javac_intg_spec.rb",
     "spec/integration/junit_intg_spec.rb",
     "spec/jar_cmd_spec.rb",
     "spec/jar_spec.rb",
     "spec/javac_cmd_spec.rb",
     "spec/javac_spec.rb",
     "spec/junit_cmd_spec.rb",
     "spec/junit_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>, [">= 0.9.1"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rubyzip>, [">= 0.9.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubyzip>, [">= 0.9.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

