require File.expand_path(File.dirname(__FILE__) + '/../../lib/java_tools')

require 'rake/clean'


CLOBBER.include('build')
CLOBBER.include('dist')


task :default => :package

task :package => [:compile, 'dist'] do
  jar 'dist/package.jar', FileList['build/**/*.class'], :base_dir => 'build', :main_class => 'com.example.HelloWorld', :verbose => true
end

task :compile => 'build' do
  javac FileList['src/**/*.java'], :destination => 'build', :verbose => true
end

directory 'build'
directory 'dist'